### PR TITLE
Feature/secure wporg urls in readme

### LINKED ISSUE #72: Prefer secure URIs when generating README
I think we should use secure URIs whenever possible.

Ex: https://wordpress.org, https://www.youtube.com, https://profiles.wordpress.org

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #72.

### CODE REVIEW

**Comment by westonruter** [comment]
@fjarrett I also tried this on a plugin and it worked: https://github.com/xwp/wp-customize-inline-editing/commit/6e0feab7e57b6b842743228cefaf015a4a497ee3

**Comment by fjarrett** [comment]
@westonruter Haha, sheesh...I'll just delete my branch then :smile: 

https://github.com/xwp/wp-dev-lib/commit/28e7058e15f3074e2efa9ff641e0e4430e7479e0

**Comment by fjarrett** [comment]
@westonruter I was thinking we could also detect when `https` was used on the YouTube links. I started some regex for that but didn't make it very far.

**Comment by fjarrett** [comment]
@westonruter Never mind... https://github.com/xwp/wp-dev-lib/commit/6af8331eac4d926856ea2683bc600586f3ff104d :+1:

**Comment by fjarrett** [comment]
@westonruter Confirmed, this worked for me on [WP Stream](https://github.com/wp-stream/stream/commit/8132dac69ad3e80f9d684f8bd2029461f525972e).

**Pull request merged**
