### PR TITLE
Load project specific phpunit bootstrap if present

### PR DESCRIPTION
**Pull request by insprintorob**

### CODE REVIEW

**Comment by westonruter** [comment]
@valendesigns brought up a good point in https://github.com/xwp/wp-dev-lib/commit/259a56d7b64f5602afe769372091c022e80ff96e

Perhaps we should revise this.

**Comment by valendesigns** [comment]
As well, if you load that file before everything else you don't have access to the variables... So it's only good for loading other dependencies and not really anything else. By loading the project specific file and returning then the project handles all the bootstrapping instead of partially.

**Comment by westonruter** [comment]
The other option would be to just copy the `phpunit.xml` into your project and then change the `bootstrap` referenced in that: https://github.com/xwp/wp-dev-lib/blob/259a56d7b64f5602afe769372091c022e80ff96e/phpunit-plugin.xml#L2

**Comment by valendesigns** [comment]
That's what I do.

**Comment by valendesigns** [comment]
It's also more flexible that way since you can edit the constants if you are creating a plugin that is never expected to be on VIP or you want to exclude other directories from being included in code coverage calculations.

**Pull request merged**
