### PR TITLE
Ensure Travis badge uses correct branch

### PR DESCRIPTION
**Pull request by valendesigns**
Setting the `DEFAULT_BASE_BRANCH` does nothing for the Travis CI branch when generating the MD file. This PR fixes that for both free and pro account.

### CODE REVIEW

**Comment by valendesigns** [comment]
@kasparsd Could you review and merge this ASAP?

**Comment by valendesigns** [comment]
@kasparsd Also, how does versioning work now? Where do we change to 1.0.2?

**Comment by valendesigns** [comment]
@kasparsd I fixed the webhook so it should be updating automatically now.

**Comment by kasparsd** [comment]
> I fixed the webhook so it should be updating automatically now.

@valendesigns Which webhook?

**Pull request merged**
