### PR TITLE
Account for xargs not doing --no-run-if-empty by default

### LINKED ISSUE #55: SVN Error when executing svn-push script
When there's no files to be deleted according [this logic](https://github.com/xwp/wp-dev-lib/blob/master/svn-push#L119) `svn rm` commands fails in syntax as it does not get any files to remove as expected.

screenshot from 2014-12-12 01 32 08

An empty string check needs to be added.

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #55.

### CODE REVIEW

**Comment by westonruter** [comment]
@desaiuditd with your :+1: I shall merge.

**Comment by desaiuditd** [comment]
Yup. I'll check n update here. :smile:

**Comment by desaiuditd** [comment]
In fact, you can merge this. Because I already tested it with one my plugin sometime back and it's already live and running.

**Comment by westonruter** [comment]
Thanks! /five @desaiuditd

**Pull request merged**
