### PR TITLE
Support for themes!

### PR DESCRIPTION
**Pull request by valendesigns**
By simply adding `BUILD_TYPE=themes` to `.ci-env.sh` you can use this library to test your themes, as well.

### CODE REVIEW

**Comment by valendesigns** [comment]
I'll add a generic theme bootstrap when I get some free time, as well.

**Comment by valendesigns** [comment]
Actually this needs to be changed. It's not backwards compatible. I'll update it tomorrow time permitting.

**Comment by westonruter** [comment]
Thanks! Also, I think `PROJECT` makes more sense than `BUILD` for these environment variables. 

Also, there should be now a `phpunit-theme-bootstrap.php` to go along with https://github.com/xwp/wp-dev-lib/blob/master/phpunit-plugin-bootstrap.php

And a `phpunit-theme.xml` to go along with https://github.com/xwp/wp-dev-lib/blob/master/phpunit-plugin.xml

**Comment by valendesigns** [comment]
I'll add the ones I created for my theme. Also, you're cool with changing the variable names? And I agree project makes more sense.

**Comment by westonruter** [comment]
Yes, those environment variables can be changed. I don't recall ever overriding them in `.ci-env.sh` or `.travis.yml`.

**Pull request closed without merging**
