### PR TITLE
Adding support for Gitter badges in README markdown

### PR DESCRIPTION
**Pull request by fjarrett**
I wanted to add support for the Gitter repo chat badge, and since their aren't any configurations to speak of, I just made an empty `.gitter` file in the project root serve as a flag.

Join the chat

On a related note, it seems like there should be a global `config.yml` or something to consolidate all the things, that's a separate issue from this, but maybe something worth thinking about?

Also I noticed that `coveralls.yml` wasn't being ignored/excluded and thought it probably should be. If that's an incorrect assumption I can remove those lines.

/cc @westonruter

### CODE REVIEW

**Comment by westonruter** [comment]
As with https://github.com/xwp/wp-dev-lib/pull/89 the `.svnignore` file is no longer used. The solution here is to modify the `rsync` command in `svn-push`.

**Comment by fjarrett** [comment]
@westonruter The solution for adding Gitter is modifying the `rsync` command?

**Comment by fjarrett** [comment]
@westonruter Oh I see what you mean now. In order to exclude the `.gitter` file from SVN push.

**Comment by fjarrett** [comment]
@westonruter That was already done here https://github.com/xwp/wp-dev-lib/commit/62885260f998b3584a6a5afca4d2fd1dfcfb38fc#diff-fe0d9a554a521257bc73e92175fa3c2aR124

And I also added a line missing to ensure `.coveralls.yml` is excluded too.

**Pull request merged**
