### PR TITLE
Suggest locking deps to specific versions

### PR DESCRIPTION
**Pull request by kasparsd**
Update npm installation instructions for how to lock to a specific release.

### CODE REVIEW

**Comment by westonruter** [comment]
@kasparsd should this include a reference to using `--save-exact`?

**Comment by kasparsd** [comment]
@westonruter Tried this in a fresh directory:

```bash
npm init --yes
npm install --save-dev --save-exact xwp/wp-dev-lib
```

and it doesn't appear to be adding a version number to the dependency:

```json
{
  "name": "dev-lib-test",
  "devDependencies": {
    "wp-dev-lib": "github:xwp/wp-dev-lib"
  }
}
```

It should be fine on repos that track the npm lock file but it would be nice to get the version string included in the dependency list.

**Comment by westonruter** [comment]
Interesting. Apparently it doesn't work with packages from GitHub. I tried:

```
npm init
npm install --save-exact xwp/wp-dev-lib
npm install --save-exact grunt
```

And I got:

```json
  "dependencies": {
    "grunt": "1.0.3",
    "wp-dev-lib": "github:xwp/wp-dev-lib"
  }
```

**Comment by kasparsd** [comment]
Now we know :)

**Pull request merged**
